// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmhYVWrlv3prN12YQQu1ElHKD7ZAFcDY',
    appId: '1:109198327288:web:82de99b52b6cdba454aa0d',
    messagingSenderId: '109198327288',
    projectId: 'notification-2fa0e',
    authDomain: 'notification-2fa0e.firebaseapp.com',
    storageBucket: 'notification-2fa0e.firebasestorage.app',
    measurementId: 'G-DY0BM4TEVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhdw7wITR0e4FWlwmQD0sEiarGUbZqzs',
    appId: '1:109198327288:android:2b40860bca03908e54aa0d',
    messagingSenderId: '109198327288',
    projectId: 'notification-2fa0e',
    storageBucket: 'notification-2fa0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmClej5J0zogB7tQrrN7QBrfYzJ7gza3g',
    appId: '1:109198327288:ios:82a8bdeb5c54a62154aa0d',
    messagingSenderId: '109198327288',
    projectId: 'notification-2fa0e',
    storageBucket: 'notification-2fa0e.firebasestorage.app',
    iosBundleId: 'com.example.taskaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmClej5J0zogB7tQrrN7QBrfYzJ7gza3g',
    appId: '1:109198327288:ios:82a8bdeb5c54a62154aa0d',
    messagingSenderId: '109198327288',
    projectId: 'notification-2fa0e',
    storageBucket: 'notification-2fa0e.firebasestorage.app',
    iosBundleId: 'com.example.taskaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmhYVWrlv3prN12YQQu1ElHKD7ZAFcDY',
    appId: '1:109198327288:web:4c91fd433b7046fc54aa0d',
    messagingSenderId: '109198327288',
    projectId: 'notification-2fa0e',
    authDomain: 'notification-2fa0e.firebaseapp.com',
    storageBucket: 'notification-2fa0e.firebasestorage.app',
    measurementId: 'G-SF1HV4SLR5',
  );
}
